made fuzzel reactive

diff --git a/linux/bin/bin/gen-color-scheme b/linux/bin/bin/gen-color-scheme
--- a/linux/bin/bin/gen-color-scheme
+++ b/linux/bin/bin/gen-color-scheme
@@ -1,21 +1,47 @@
 #!/bin/bash
+
+REQ_PROGRAMS=("jq" "ffmpeg" "waytrogen" "sed")
+REQ_PROGRAM_NOT_FOUND="false"
+for PROGRAM in "${REQ_PROGRAMS[@]}"; do
+  if (! command -v "$PROGRAM" >/dev/null); then
+    echo "${PROGRAM} not found. Please install it."
+    REQ_PROGRAM_NOT_FOUND="true"
+  fi
+done
+
+if [ "$REQ_PROGRAM_NOT_FOUND" = "true" ]; then
+  exit 1
+fi
+
 OUTPUT="$HOME/.config/waybar/colors.css"
 rm -f "$OUTPUT"
 WALLPAPERS="$(waytrogen -l | jq -r -c '.[] | select(.monitor != "")')"
+FG_COLOR_QUERY=".colors.on_primary.default.color"
+BG_COLOR_QUERY=".colors.primary.default.color"
+IS_FIRST_WALL=""
 echo "$WALLPAPERS" | while IFS=$'\n' read -r wallpaper; do
-  MONITOR="$(jq -r '.monitor' <<< "$wallpaper")"
-  WALL_PATH="$(jq -r '.path' <<< "$wallpaper")"
+  MONITOR="$(jq -r '.monitor' <<<"$wallpaper")"
+  WALL_PATH="$(jq -r '.path' <<<"$wallpaper")"
   TMP_THUMBNAIL="/tmp/thumbnail.jpg"
-  IS_MPVPAPER="$(jq -r '.changer.MpvPaper' <<< "$wallpaper")"
+  IS_MPVPAPER="$(jq -r '.changer.MpvPaper' <<<"$wallpaper")"
   if [ "$IS_MPVPAPER" != "null" ]; then
     ffmpeg -nostdin -i "$WALL_PATH" -vf "select=eq(n\,0)" -q:v 3 "$TMP_THUMBNAIL" -y -hide_banner -loglevel error
     WALL_PATH="$TMP_THUMBNAIL"
   fi
+  if [ -z "$IS_FIRST_WALL" ]; then
+    IS_FIRST_WALL="true"
+    FUZZEL_OUTPUT="$HOME/.config/fuzzel/fuzzel.ini"
+    TEMPLATE="$HOME/.config/fuzzel/fuzzel.tmpl.ini"
+    COLOR_SCHEME="$(matugen image "$WALL_PATH" --prefer=darkness --json hex)"
+    FG_COLOR="$(jq -r "$BG_COLOR_QUERY" <<<"$COLOR_SCHEME" | tr -d '#' | sed -E 's/$/ff/g')"
+    BG_COLOR="$(jq -r "$FG_COLOR_QUERY" <<<"$COLOR_SCHEME" | tr -d '#' | sed -E 's/$/ff/g')"
+    sed -E "s/@BG_COLOR@/${BG_COLOR}/g" "$TEMPLATE" | sed -E "s/@FG_COLOR@/${FG_COLOR}/g" >"$FUZZEL_OUTPUT"
+  fi
   COLOR_SCHEME="$(matugen image "$WALL_PATH" --prefer=darkness --json rgba)"
-  FG_COLOR="$(jq -r '.colors.on_primary.default.color' <<< "$COLOR_SCHEME")"
-  BG_COLOR="$(jq -r '.colors.primary.default.color' <<< "$COLOR_SCHEME" | sed -E 's/1\)$/0.7\)/g')"
-  echo "@define-color color${MONITOR} $FG_COLOR;" >> "$OUTPUT"
-  echo "@define-color bgcolor${MONITOR} $BG_COLOR;" >> "$OUTPUT"
+  FG_COLOR="$(jq -r "$FG_COLOR_QUERY" <<<"$COLOR_SCHEME")"
+  BG_COLOR="$(jq -r "$BG_COLOR_QUERY" <<<"$COLOR_SCHEME" | sed -E 's/1\)$/0.5\)/g')"
+  echo "@define-color color${MONITOR} $FG_COLOR;" >>"$OUTPUT"
+  echo "@define-color bgcolor${MONITOR} $BG_COLOR;" >>"$OUTPUT"
   if [ -e "$TMP_THUMBNAIL" ]; then
     rm -f "$TMP_THUMBNAIL"
   fi
